model_type: 1
model_name: GAT



cuda_name: cuda:0

# work_dir: GAT_GCN
work_dir: test
batch_size: 
  train: 256 
  val: 256
  test: 256 
lr: 0.00005
num_epoch: 300
log_interval: 50
seed: 171

dataset_name: GDSCv2

dataset_type: 
  - GDSCv2_train_mix_useChirality
  - GDSCv2_val_mix_useChirality
  - GDSCv2_test_mix_useChirality

model:
  
  drug_module: 
    module_name: 
      - GATConv
      - GATConv
    input_drug_feature_dim: 90
    output_drug_feature_dim: 128
    layer_num: 2

    gnn_layers: 
      - 
        intput: 90
        output: 900
        dropout: 0.2
        feature_pre_dropout: 0.2
        heads: 10
      - 
        intput: 900
        output: 128
        dropout: 0.2
        feature_pre_dropout: 0.2
        heads: 1

    linear_layers:
      - 
        operate_name: linear
        param:
          - 128
          - 128
      - 
        operate_name: relu


      # - 
      #   operate_name: linear
      #   param:
      #     - 1800
      #     - 1500
      # - 
      #   operate_name: relu
      # - 
      #   operate_name: dropout
      #   param: 0.2
      
    graph_pooling: max
    dropout: 0.5

  cell_module: 
    module_name: Conv1d
    input_cell_feature_dim: 735
    output_cell_feature_dim: 128
    fc_1_dim: 128
    layer_num: 3
    layer_hyperparameter:
      kernel_size:
        - 8
        - 8
        - 8
      maxpool1d: 
        - 3
        - 3 
        - 3
      cnn_channels:
        - 32
        - 64
        - 128


  fusion_module:
    fc_1_dim: 1024
    fc_2_dim: 128
    fc_3_dim: 1
    dropout: 0.5
    fusion_mode: concat
