model_type: 3
model_name: tCNNs



cuda_name: cuda:0

work_dir: tCNNs_GDSCv2
batch_size: 
  train: 256 
  val: 256
  test: 256 
lr: 0.00005
num_epoch: 300
log_interval: 50
seed: 171

dataset_name: GDSCv2

dataset_type: 
  - GDSCv2_train_mix_useChirality_withTTC
  - GDSCv2_val_mix_useChirality_withTTC
  - GDSCv2_test_mix_useChirality_withTTC

model:
  
  drug_module: 
    module_name: Conv1d
    input_drug_feature_channel: 33
    input_drug_feature_dim: 193
    layer_num: 3
    layer_hyperparameter:
      kernel_size:
        - 7
        - 7
        - 7
      maxpool1d: 
        - 3
        - 3 
        - 3
      cnn_channels:
        - 40
        - 80
        - 60

  cell_module: 
    module_name: Conv1d
    input_cell_feature_dim: 735
    fc_1_dim: 128
    layer_num: 3
    layer_hyperparameter:
      kernel_size:
        - 7
        - 7
        - 7
      maxpool1d: 
        - 3
        - 3 
        - 3
      cnn_channels:
        - 40
        - 80
        - 60


  fusion_module:
    fc_1_dim: 1024
    fc_2_dim: 1024
    fc_3_dim: 1
    dropout: 0.0
    fusion_mode: concat
